spring.application.name=backend

spring.datasource.url=jdbc:postgresql://localhost:5432/sairam_fancy_billing
spring.datasource.username=postgres
spring.datasource.password=Abhi@3026

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true